# Generated by Django 5.0.2 on 2024-02-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, default='images/questionmark.jpeg', null=True, upload_to='images/')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
