# Generated by Django 5.0.2 on 2024-02-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_number',
            field=models.CharField(default='ORD-9522', max_length=10),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('serving', 'Serving')], default='preparing', max_length=20),
        ),
    ]
